package main

import (
	"encoding/xml"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

type xmlURLSet struct {
	XMLName xml.Name `xml:"urlset"`
	Xmlns   string   `xml:"xmlns,attr"`
	URLs    []xmlURL `xml:"url"`
}

type xmlURL struct {
	Loc      string `xml:"loc"`
	Priority string `xml:"priority"`
}

// pathDepth returns the number of path segments ("/" → 0, "/a/b" → 2).
func pathDepth(path string) int {
	trimmed := strings.Trim(path, "/")
	if trimmed == "" {
		return 0
	}
	return len(strings.Split(trimmed, "/"))
}

// computePriorities calculates the sitemap priority for each page using the original
// heuristic (depth + incoming links) but perfectly normalized so the top page is 1.0.
func computePriorities(state *CrawlerState, history *ChangeHistory) map[string]float64 {
	maxIncoming := 0
	for _, in := range state.incoming {
		if in > maxIncoming {
			maxIncoming = in
		}
	}

	rawScores := make(map[string]float64)
	maxRaw := 0.0

	for norm := range state.paths {
		in := state.incoming[norm]
		var inScore float64
		if maxIncoming > 0 {
			inScore = math.Log1p(float64(in)) / math.Log1p(float64(maxIncoming))
		}

		depth := pathDepth(state.paths[norm])
		depthScore := 1.0 / math.Pow(2.0, float64(depth))

		var ph *PageHistory
		if history != nil {
			ph = history.Pages[norm]
		}

		var p float64
		if ph != nil {
			p = 0.55*inScore + 0.20*depthScore + 0.25*ph.score()
		} else {
			p = 0.70*inScore + 0.30*depthScore
		}

		rawScores[norm] = p
		if p > maxRaw {
			maxRaw = p
		}
	}

	// Normalize relative to the highest scoring page to ensure max is 1.0
	finalScores := make(map[string]float64)
	for norm, r := range rawScores {
		var p float64
		if maxRaw > 0 {
			p = r / maxRaw
		} else {
			p = 1.0
		}
		finalScores[norm] = math.Max(0.1, math.Min(1.0, p))
	}
	return finalScores
}

// writeXML generates an XML sitemap from the crawl state and writes it to
// outFile. When history is non-nil, page-change scores influence priorities.
func writeXML(state *CrawlerState, outFile string, history *ChangeHistory, pr map[string]float64) (err error) {
	entries := make([]xmlURL, 0, len(state.paths))
	for norm := range state.paths {
		entries = append(entries, xmlURL{
			Loc:      norm,
			Priority: fmt.Sprintf("%.2f", pr[norm]),
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Priority > entries[j].Priority
	})

	urlset := xmlURLSet{
		Xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9",
		URLs:  entries,
	}

	f, err := os.Create(outFile)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); err == nil {
			err = cerr
		}
	}()

	if _, err = f.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"); err != nil {
		return err
	}
	if _, err = f.WriteString("<!-- Generated by github.com/velox0/creeper -->\n"); err != nil {
		return err
	}

	enc := xml.NewEncoder(f)
	enc.Indent("", "  ")
	if err = enc.Encode(urlset); err != nil {
		return err
	}
	return nil
}
